### ISSUE TITLE
Long Duration Issue on 0_2 

### ISSUE THREAD

**Issue by ProdigizedDP** [Dustio/Gunkolle#1]
**Desktop:**
What graphics card are you using?
NVIDIA GeForce GTX 1080

**Config File:**
[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=3000
MinRandomWaitS=3000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class LDPlayerMainFrame
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=FAL
Doll2=G11
Doll3=ERROR
Doll4=ERROR
WeaponType=AssaultRifle
Enhancement=0
ProductionTdoll=0
ProductionEquipment=0
FriendCollector=0
BatteryCollector=0
AutoBattleResend=0
WorldSwitcher=0_2
LastXS=3366
LastYS=769
[GPU]
AMD=0
#For AMD or others GPU's change value 0 to 1. For NVidia value must be 0

#combatsims can be of values 1,2, or 3
CombatSimsData=2

**Describe the bug**
I've been having an issue running the bot for a long period of time 5-8 hours. I usually leave the bot running unattended if I'm at work / sleeping, so if something goes wrong it ends up sitting there for the rest of the time until I'm back to set it back up again. I've been doing 0_2 runs and recently I've had the bot say that the current echleon doesn't have ammo or rations to continue, which means Doll 1 & 2 weren't swapped for the corpse drag. Just wanted to check if this comes up in your runs or if it's just me. 

On a side note on the other issue I have on echocontrols github, I restarted my pc and i was able to get the map 3-1 working for five-seven, but I don't have low cooldown dolls to kill the black beans resulting in failed runs. If it isn't a hassle i'd like to request a constant for the map E1-C2 to farm Five-Seven. It looks like it'd be rather simple to write the script for as it just requires the echleon drop, planning for 5 or 6 nodes and then ending and restarting. I would map it myself, but I don't reallly understand how to find the ClickS coordinates for the window. When I did the last event I was using EchoControls and was able to just use the image search before. Look forward to a response, thanks again. 

**Screenshots**
Image Relevant to the update below
![dnplayer_4XLqDnMtLY](https://user-images.githubusercontent.com/14143426/70387676-c752cf00-195c-11ea-9290-a9e48270d3c1.png)

Also if you have a discord by chance, I'd be interested in adding you. Thanks :)

Update: This happened as I was about to sleep, but it was trying to switch my G11 & FAL around, and instead of them being swapped it said the doll being chosen was in logistics (my zas) so i'm not sure if there was a change or something being made to how it picks the doll in the formation, but it didn't correctly click my FAL.

**Comment by Dustio** [comment]
I don't usually run maps for more than 2 hours, so I don't really get this issue. I can think of a couple of things going wrong here. One is that the client might be lagging, and I can make the sleep longer to make sure the images appear completely before it searches. It kinda sucks that I had to remove the ProfileWait click with the client update a while ago and have to rely sleep again. For now I'll increase sleep time in ReplaceDPS. Another possible problem is the doll images themselves - might need to adjust the size of them or something. 

If you have 2 ROF buffers for your M4 you should be able to kill the beans in 3-1. To find the coords for ClickS use WindowSpy that came with your AutoHotKey package. I can make the map if you still need me too later, hope this helps.

**Comment by ProdigizedDP** [comment]
It turns out Girls Frontline was having lag across the server for about 2 days, I believe that was the issue for not being able to swap T-Dolls.
