### ISSUE TITLE
Not withdrawing from ambush on 4_6 Data.

### ISSUE THREAD

**Issue by yocool13** [Dustio/Gunkolle#10]
**Desktop:**
GTX 1060

**Config File:**
[config.txt](https://github.com/Dustio/Gunkolle/files/4318555/config.txt)

**Describe the bug**
It seems the script sometimes just doesn't retreat when there's an ambush when walking over a random node on 4-6 Data. This doesn't seem to happen _very_ often. Maybe it retreats too late? Or maybe it fails to click the pause button because of lag?

**Screenshots**
![uh oh](https://user-images.githubusercontent.com/10333247/76423268-c6d83300-63a6-11ea-952d-5dd92b04b277.png)

**Comment by Dustio** [comment]
Yeah I've had this problem too, the timing on the pause click seems very finicky. I've tried almost every findclick function to make it consistent but they all seem to run into a problem. To make it more consistent, I went with ClickTilGone, which clicks the pause button until it goes away, but then when it lags a little, it clicks it twice and un-pauses. 

To fix that, I added a fail-safe click after to check if it is actually paused, maybe adding another one to each FoundBattle could help. 

``
sleep 500
``
``
FoundPause := FindClick(A_ScriptDir "\pics\Maps\4_6\CombatPause", "rLDPlayer mc o40 Count1 n1 w250")
``

I'll do a small update with this, not sure how much it will help.

**Comment by yocool13** [comment]
It seems the `FoundPause := FindClick(A_ScriptDir "\pics\Maps\4_6\CombatPause", "rLDPlayer mc o40 Count1 n1 w250")` line was present in the script, but it didn't have the `sleep 500` before it. Adding this seemed to have (mostly) fixed this.

**Comment by Fatal-Pulse** [comment]
It seems to be that a very minimal amount of lag will contribute to thee failure of the ambush check, seen here (laptop running on wifi) https://streamable.com/6rpdqc

Maybe a fix for this could be to increase the ambush timer but really depends on how laggy the user's connection is.
