### ISSUE TITLE
Three star retirement on 0-2 not working.

### ISSUE THREAD

**Issue by yocool13** [Dustio/Gunkolle#11]
**Desktop:**
GTX1060

**Config File:**
_Visible in screenshot_

**Describe the bug**
0-2 corpse drag seems to hang up on ThreeStar during retirement. It also didn't scroll down, which I think it was supposed to?
Script hung up on _5-Star filtering_ before, but this was fixed by replacing the image. Although here it doesn't seem to be the same problem, because the filter menu isn't open, whilst it was on the 5_Star filtering problem.

I also included a screenshot of the script running thing, not sure if that helps. I can't figure out whats wrong with it from looking at that however.

**Screenshots**
![uh oh2](https://user-images.githubusercontent.com/10333247/76529817-1be17b00-6473-11ea-9bc1-869d16094b30.png)
![uh oh1](https://user-images.githubusercontent.com/10333247/76529824-1e43d500-6473-11ea-8d22-d4a06932103d.png)

**Comment by Dustio** [comment]
It's working on my end, so I would guess that is is the pics of "Filter" and "ThreeStar". Also your client doesn't have a 6-Star option while mine does. Retirement doesn't use any scrolling; it smart selects all 2-stars, then findclicks Filter then ThreeStar then Confirm.

**Comment by yocool13** [comment]
This is all still using the old client, right?

**Comment by Dustio** [comment]
Yes, I'm using the apk from the reddit link in the readme.

**Comment by yocool13** [comment]
Yeah, replacing the pics fixed the issue. No clue why it stopped working.
