### ISSUE TITLE
Mica has issued bans to players, as announced via their twitter. Just a warning, as I'm unsure if this is related to this particular script, or other forms of cheating.

### ISSUE THREAD

**Issue by SwordfishWithGlasses** [Dustio/Gunkolle#12]
I'm pretty sure gunkolle has built in delays that randomize to avoid cheat detection, but it would be comforting to confirm if this is the case and that it's actually working.

**Comment by Dustio** [comment]
Yeah FindClick is random and ClickS has an offset of 10 currently. There's always a chance that they could make the way that they detect automation more advanced to look at patterns over time, but I doubt that's the case or that they can be 100% and ban with that info. 

I would guess that tons of players have tried macros before and only a handful get banned, so you either have to really mess up and make it obvious (like by clicking the same spot over and over), or actually cheat by modifying data or refunding purchases.
