### ISSUE TITLE
Potential to add feature for auto logisitcs rerun?

### ISSUE THREAD

**Issue by SwordfishWithGlasses** [Dustio/Gunkolle#14]
Hey again! I find that I post too much in this thread, and I want to firstly say that you've done a great job adapting this project from its past versions. Hopefully it isn't too annoying to see the issues thread being used for these feature requests!

Anyway, I think it would be a great addition to add a feature to gunkolle that simply performs checks on the main menu screen for if a logistic mission needs to be restarted. Currently the script does this in between runs, but sometimes I find there are moments where I just want to farm the low-duration logistics instead of spending on data farm (which drains resources at rng) or corpse dragging. This would be especially helpful for resource oriented logistic missions (such as 3-1), which run on low timers and despite not granting contracts, are very good for overall resource gain.

**Comment by Dustio** [comment]
Thanks, I will try to keep updating as long as I am still playing. I think we already have what you are looking for in the "Expedition only" checkbox. Just click that and then start, can be hovering any map.

**Comment by SwordfishWithGlasses** [comment]
Ah that makes sense actually. Could you also clarify what the sort 1/2 options do? I think you added these a few months ago but I can't find anything on it. 

Thanks again.

**Comment by Dustio** [comment]
Sure np. The "lose connection" should only happen when a picture of an "X" pops up to close windows, so I use it for detecting maintenance during expedition only. For me, it doesn't ever pop up unless I forget to pause and do fairy crafts while it is running. 

The sort buttons were added in case you want to corpse drag with dolls that aren't on the first page after filtering rarity and type. When switching dolls in formation, it will drag the screen down to see more dolls - Sort2 will drag further.
