### ISSUE TITLE
Recommended Corpse Drag Map Additions 8-1N

### ISSUE THREAD

**Issue by SwordfishWithGlasses** [Dustio/Gunkolle#16]
2 Maps which are missing from the pool of specialized drag runs are 8-1N and 11-5. 8-1N is an improved 6-3N, and 11-5 is a much much harder and very slightly better 0-2, although not for the majority of players. 

8-1N is just a straight up improved 6-3N for the purposes of grinding though, and for most players who can already do zas runs the higher FP requirements are not a big deal. 

8-1N would be a great addition to the standard map pool of gunkolle should you have the time. 

Once 12-4e hits EN that would be an amazing addition, as it is the next step up from 0-2.

**Comment by Dustio** [comment]
We already have 8-1N in the latest. I will add 11-5 once I get around to clearing it lol.
