### ISSUE TITLE
E1_1 has issues dismantling 3 star units, and just gets caught on the screen. 

### ISSUE THREAD

**Issue by SwordfishWithGlasses** [Dustio/Gunkolle#17]
I haven't tested this with the other event maps, but thought it worth mentioning, even if the event is almost over.

**Comment by Dustio** [comment]
It got stuck on the 3-star retire select screen? I think I can just slow do the clicks during retirement since every map should be the doing the same thing while retiring dolls.

**Comment by SwordfishWithGlasses** [comment]
In my experience this is a consistent problem with 1_1 but doesn't seem to happen as often with something like 0-2
