### ISSUE TITLE
Gunkolle gets stuck on filtering 5STAR units when trying to drag 0-2.

### ISSUE THREAD

**Issue by SwordfishWithGlasses** [Dustio/Gunkolle#18]
**Desktop:**
EVGA GTX1070 FTW

**Config File:**
Post your Config File
![Config](https://user-images.githubusercontent.com/59255537/82719489-9ea36500-9c70-11ea-974b-717347199f19.png)

Sorry I'm having so many issues running gunkolle at the moment. 

For some reason the script gets caught here at 5STAR filtering, and doesn't move onto corpse dragging the map. No matter what dolls I input in the config, this does not change. This also applies to other dolls I add myself. 

I've tried running older versions of the script that did work for me (such as .73 and .74) but they all run into the same issue. This has to be a specific thing to my hardware, but I am still at a loss as to what that would be. 

**Screenshots**
![Stuck at 5Star](https://user-images.githubusercontent.com/59255537/82719551-62bccf80-9c71-11ea-8893-156478bf9833.png)

**Comment by Dustio** [comment]
I remember someone else had this issue too. Taking a new pic of 5STAR should fix this, probably 3STAR  in retirement as well. Your client doesn't have the 6-Star filter option like mine does, idk if you need to unlock NTW mod 3 or what to change that.

**Comment by SwordfishWithGlasses** [comment]
Looks like not having NTW mod 3 was the source of the issue. After unlocking her mod 3 the sorting works fine on both the event map and 0-2. Would probably be something important to consider for players who don't have access to NTW, but good to know about regardless. 

Thanks!
