### ISSUE TITLE
4-6 Data Heliport Deployment

### ISSUE THREAD

**Issue by BobbyDuggart** [Dustio/Gunkolle#20]
4-6 Data has always been finicky for me. My computer must be slow as shit because when I first ran 4-6 successfully, I had to increase the sleep timers by about 300% lol. 4-6 is currently working, but there's one problem, that being the command post deployment. On Nox, the command post is right next to the green "App Center" button. On the default ClickS positions, Gunkolle would sometimes click the button and bring me to the app store. I remedied this by simply moving the Y value down, but now it often misses the command post entirely and does the run without any top echelon. Is there a way to ClickS within a predefined area? Or maybe I should swap to image searching? I would just reduce the offset, but I'm not sure how much can I do that without getting flagged for macroing.
Thanks again for your work on this project.

**Comment by Dustio** [comment]
I think the area should be big enough to click consistently (20 pixels), might just need to find the right y value unless the app center button is set over the screen. Image search didn't work the last time I tried for this click. 

I choose the sleep timers so that it runs consistently on my pc even after lots of runs and slowdown, so if your pc/internet is slower they might need to be adjusted.

I recently starting to test 4_6 again and made a few changes that make it more consistent, like checking if the heliport was clicked and pause/retreat in combat. After I'm done testing more I'll update.

**Comment by BobbyDuggart** [comment]
So 20 pixels is the range in which ClickS randomly clicks? if that's the case I should be able to make it work. lemme mess around with it a bit more

**Comment by BobbyDuggart** [comment]
okay I figured out the problem, but first, lemme just clarify that I was talking about the heliport instead of the command post. I thought the top node was the command post, turns out it's the heliport.

When deploying an echelon onto the heliport, the clickable range is y48 to y76. This is fine, it deploys an echelon every time consistently.

When clicking on an echelon on the heliport, the clickable range is y48 to y68.

What's happening is, it's deploying the echelon onto the command post, then the heliport, starting the operation, and then failing to click on the echelon on the heliport, then clicking node1, 2, 3, and 4, without moving the echelon.

y48 to y68 is 20 pixels, so if the offset is 20 pixels it should click every time, but I think it's bigger than that because it's not clicking the echelon about 40% of the time.

Any help is appreciated.

**Comment by Dustio** [comment]
Oh yeah I assumed you meant the heliport. So if the coordinate goes any higher it will click the app center button? On LDplayer there is barely enough room for me. I will update in a little bit with a fix that FatalPulse made for the new client a while ago, where you need a command fairy in echelon 2 to check if the echelon has been clicked and can start moving.

**Comment by BobbyDuggart** [comment]
that fixed the problem! thanks epic gamers
