### ISSUE TITLE
Compulsory Client Update

### ISSUE THREAD

**Issue by BobbyDuggart** [Dustio/Gunkolle#21]
A forced update to the new version? does this mean Gunkolle is kill?

**Comment by Dustio** [comment]
No, I need to include the changes from the new client branch into the current one. I just hope the new client doesn't have the crashing issue anymore.

**Comment by BobbyDuggart** [comment]
fuck yea, thanks gamer. btw you say "new client branch" like other people are working on Gunkolle as well. is it just you or is there some other github that im missing out on?

**Comment by Dustio** [comment]
About 2 months ago I made a branch for this repo that works on the new client, it needs a few pics updated to work now. It's below "master" branch.

**Comment by BobbyDuggart** [comment]
oh damn I didn't even notice that. I thought this client was dead on update haha, thanks once again for your work!

**Comment by Dustio** [comment]
Yup np, master is up to the new client now.
