### ISSUE TITLE
10-4E AMD

### ISSUE THREAD

**Issue by BuffaloFrail** [Dustio/Gunkolle#23]
Hi, have an issue in 10-4E where the script will resupply the command post rather than the top helipad at the start of a run. Should be able to find a fix, just thought I would let you know. I'm using an AMD card as well so this might be the reason why. Thanks!

**Comment by Dustio** [comment]
That is working as intended, 10_4E is for corpse dragging, so it resupplies a solo unit and retreats it. 10_4Ecdo has it off, and resupplies the top heli. I did notice that the wiki is missing some dummy echelons for 10_4Ecdo so I will add them now.

**Comment by BuffaloFrail** [comment]
Ah, I see! my mistake, haha, apologies.
