### ISSUE TITLE
Would it be possible to add the third map for the Snowy Night Capriccio event as well?

### ISSUE THREAD

**Issue by sjk0603** [Dustio/Gunkolle#3]
I noticed that there's one for the first map to grind 60 stars. Would it be possible to add the third map as well?

**Comment by Dustio** [comment]
Do you need it to farm for Px4 or other reasons too?

**Comment by sjk0603** [comment]
Yup, it is to farm that gun.

**Comment by sjk0603** [comment]
Thank you for adding the map!
