### ISSUE TITLE
Would you be able to add AN-94 to the available dolls? Also, Bluestacks compatability? 

### ISSUE THREAD

**Issue by SwordfishWithGlasses** [Dustio/Gunkolle#4]
AN is a really good DPS doll, and it would be great to have her available. She's even or better than g11 in most cases.

Also, is there a way to adapt the script to Bluestacks? I was tinkering with the functions from echo's version in Notepad++, but wasn't able to get past a reported "invalid screen," even though I got the script to recognize the window.

**Comment by Dustio** [comment]
Sure, can add her. I'm not 100% sure about Bluestacks but I think the window size might be bigger than LDPlayer and the rendering is different. Maybe try and replace the WaitForHome pic with your own and see if it recognizes the screen? If it does, you would need to replace all pics and coordinates for the rest to work.

**Comment by SwordfishWithGlasses** [comment]
Cool! I'll give it a shot. 

A thought that came to mind while I was testing the script however was that technically, it would be most efficient for max level draggers to be in position 2-5, not 1, as the captain of the team receives bonus exp. I think that a toggle-able option for this would make a lot of sense. From what I can tell, it would involve changing the coordinates under

WFindClick("DollList\"%exhaustedDoll% , "rLDPlayer mc a125,125,-590,-220", 120) ;select Doll1


I'm not sure how I would add this to the script's initial options menu however, because I'm a noob coder :/

**Comment by Dustio** [comment]
It should be finding dolls in either slot 1 or 2 with the current code, so you can put a low level tdoll as the captain. If you wanted to put draggers in more slots you would want to increase the width of the search area, which is set to -590 right now. So changing -590 to -390 will let you search for it in slot 3 and 4 too. 

I don't have much knowledge in code either, I've just been looking through this code and figuring it out as I go too :p That line for doll selection is pretty old so it may not be optimized, but it works still so I haven't put too much thought into it.
