### ISSUE TITLE
Stuck on new  4-6 Data on retreat

### ISSUE THREAD

**Issue by MiniWa-N** [Dustio/Gunkolle#5]
**Desktop:**
What graphics card are you using?
NVIDIA GeForce GTX 1060 6GB
**Config File:**
Post your Config File
[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=3000
MinRandomWaitS=3000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class LDPlayerMainFrame
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=FAL
Doll2=M4SOPMODII
Doll3=ERROR
Doll4=ERROR
WeaponType=AssaultRifle
Enhancement=0
ProductionTdoll=0
ProductionEquipment=0
FriendCollector=0
BatteryCollector=0
AutoBattleResend=0
WorldSwitcher=4_6_data
LastXS=174
LastYS=781
[GPU]
AMD=0
#For AMD or others GPU's change value 0 to 1. For NVidia value must be 0

#combatsims can be of values 1,2, or 3
CombatSimsData=2

**Describe the bug**
The new 4-6 Data script works way faster than older one that is for sure, but it is not correctly retreating and getting stuck when the echelon gets ambushed. On the screenshot I attach m16 is at the middle position stopping from the enemies from flying and giving failure, however even m16 is at the bottom position and let the fail happen the script gets stuck on the  afterbattle screen

**Screenshots**
https://puu.sh/EWb1H/f75c8615b1.png

**Comment by Dustio** [comment]
What does the GUI say when it fails? Does this occur every battle encounter? If it does, it probably has something to do with the pics for 4_6. You could try to make your own Ambush/CombatPause pics and see if it still fails. Everything works fine on my end, I tested probably over 1000 resets without problems. I can add the old map if that works better still.

**Comment by MiniWa-N** [comment]
https://puu.sh/EWojl/ce069db40d.png

It says Waiting for [\Maps\4)6\Withdraw)
It happens every battle.

I would wait for more people to report a problem maybe? Personally I still have the older version of the script with the older route, but I am interested because the new one you made is really much faster.

Let me figure out how to change those images and I will report back

**Comment by MiniWa-N** [comment]
Changed Pause image and it seems to be actually pausing now
![CombatPause](https://user-images.githubusercontent.com/58696108/71771352-49acbf80-2f18-11ea-8508-4a340086c3f6.png)

However I am having trouble setting up the withdraw button, I wonder if it is because it flashes instead being an static image.

**Comment by Dustio** [comment]
Yeah I'm not sure why some pics aren't working for other people, but at least making your own works for now.

You need to use a part of withdraw that isn't transparent, so that the background doesn't bleed through since nodes have different backgrounds. That's why I had a small pic for withdraw.

**Comment by MiniWa-N** [comment]
I... am not sure what part of that  thing is even not transparent... do you think it would be more stable if we used coordinates instead pixel finding for this?

**Comment by Dustio** [comment]
Just to clarify, have you tried your new CombatPause pic with the old Withdraw pic? If that's not working then coords will probably work.

**Comment by MiniWa-N** [comment]
Yes, I also tried with the old withdraw picture with no luck. I am new to coding on general, so far I learned I can check the coords using window spy, how would I go to code to click on that coords instead search for picture?

**Comment by Dustio** [comment]
Okay so I replaced these two lines in Maps.ahk

TFindClick("\Maps\4_6\CombatPause","\Maps\4_6\Withdraw", sleep250)
ClickTilGone("\Maps\4_6\Withdraw", " rLDPlayer mc o10 w30000,50")

with these

RFindClick("\Maps\4_6\CombatPause", "rLDPlayer mc o10 w30000,50 ")
sleep 500
ClickS(426, 66)

I uploaded the change to 4_6-test branch since I haven't tried it  much, and I don't know if more people have this issue.

**Comment by MiniWa-N** [comment]
I tried just now the new 4-6-test branch. I still have to substitute the pause image for the one I showed before, however now the withdraw works.  Everything seems to be working like a charm, I will leave it running for some hours and report back. Thanks a lot by the way

**Comment by MiniWa-N** [comment]
Did over 1k runs, had a few hiccups there and here but that's probably because some internet instability on my side, this new code should work for people who have trouble setting the withdraw image, thanks again!

**Comment by Dustio** [comment]
Nice, I think the last time I tried using RFindClick for pause it wouldn't click sometimes, but I'll try it again next time I run the map. For now I'm waiting for fairy rate up.
