### ISSUE TITLE
Using 960x540 resolution?

### ISSUE THREAD

**Issue by sjk0603** [Dustio/Gunkolle#6]
After a quick look at how the maps function, it looks like I'll have to enter new coordinates and redo the images if I were to run the emulator on the 960x540 resolution (the smallest one available for LD Player), but what does this particular error signify? It seems like it has something to do with establishing a search area, which I assume is the LD Player window, but that's as far as I can assume with my limited knowledge.

![2020-01-04_02-41-50](https://user-images.githubusercontent.com/43340980/71762350-19bfd680-2e9c-11ea-9554-8226d7e7d6dd.png)

**Comment by Dustio** [comment]
You need to edit the function Window.ahk and set the area parameters for the two searches on lines 15 and 67.  Removing the area search can be a quick fix but I'm not sure if that breaks anything.

**Comment by sjk0603** [comment]
Oh man, this seems rather complicated. You're referring to these lines right?

15- FindClick(A_ScriptDir "\pics\WaitForHome", "rLDPlayer mc o30 Count1 n0 a1200,,,-600")

67- FoundHomeScreen := FindClick(A_ScriptDir "\pics\WaitForHome", "rLDPlayer mc o30 Count1 n0 a1200,,,-600")

Which value would I have to adjust?

**Comment by Dustio** [comment]
Remove/adjust 1200 and -600, the values for the area options. I'm not sure how to adjust them to the new resolution.

**Comment by sjk0603** [comment]
Oh snap, okay so I set it to "a900,,,-400" so that it would look something like this:

FoundHomeScreen := FindClick(A_ScriptDir "\pics\WaitForHome", "rLDPlayer mc o30 Count1 n0 a900,,,-400")

It successfully managed to check for the home screen without any errors. I do get a second error once I start the script which appears to be a similar error:

![2020-01-04_09-59-19](https://user-images.githubusercontent.com/43340980/71767301-0121e180-2ed9-11ea-8f06-b5603dbef000.png)

It seems like there are other area perimeters that I have to edit. I'm going to try to fiddle with it a bit and report back, thanks for your help!

**Comment by Dustio** [comment]
No problem! I recommend looking through FindClick.ahk to better understand the options for image search.

**Comment by sjk0603** [comment]
Okay, so from what I can tell it seems like the function that's meant to make each clicks be dynamic so it doesn't click the same spot every time makes it miss certain spots sometimes, since everything is much smaller at this resolution. I guess I'll go back to the old resolution!
