### ISSUE TITLE
How to setup for the CT maps?

### ISSUE THREAD

**Issue by MiniWa-N** [Dustio/Gunkolle#8]
I am sorry if you already described on how to adjust in game for the macro to work, but if not, can you give us some details on how to?

**Comment by Dustio** [comment]
Sure, it's currently using findclick to search for event maps. To use each map you need to zoom out and start operation in whatever map you want to use, so you can just spawn a dummy and then terminate if you want. Then go home and start the script. Starting any other map will reset the position of the event map, so it has to be the last map you played.

**Comment by MiniWa-N** [comment]
oh I see how it works now, thanks a lot!
